
{$I q500_dt.inc}
{.$I q500_en.inc}

resourcestring                                     {Länderneutrale strings}

  fmAltitude='Altitude mode';
  fmStabilized='Manual/Stabilized mode';
  fmRattitude='Rattitude mode';
  fmPosition='Position mode';
  fmMission='Mission mode';
  fmAngle='Angle mode';
  fmSmart='Smart mode';
  fmManual='Manual mode';
  fmRTH='RTH';
  fmSportMode='Sport Mode';
  fmSportSmartMode='Sport/Smart Mode';
  fmAgility='Agility Mode (Rate)';
  fmStability='Stability Mode (Blue solid)';
  rsUndef='Undef';

  rsHDcell1='fsk_rssi';
  rsHDcell2='voltage';
  rsHDcell3='current';
  rsHDcell4='altitude';
  rsHDcell5='latitude';
  rsHDcell6='longitude';
  rsHDcell7='tas';
  rsHDcell8='gps_used';
  rsHDcell9='fix_type';
  rsHDcell10='satellites_num';
  rsHDcell11='roll';
  rsHDcell12='yaw';
  rsHDcell13='pitch';
  rsHDcell14='motor_status';
  rsHDcell15='imu_status';
  rsHDcell16='press_compass_status';
  rsHDcell17='f_mode';
  rsHDcell18='gps_status';
  rsHDcell19='vehicle_type';
  rsHDcell20='error_flags';
  rsHDcell21='gps_accH';

  csvTime='Time';
  csvSWload='SW load';
  csvVolt='voltage';
  csvAmp='current';
  csvUcap='Batt used';
  csvAlt='altitude';
  csvAltMSL='Altitude MSL';
  csvHeading='Heading';
  csvLat='lat';
  csvLon='lon';
  csvCap='Batt remain';
  csvGPSfixT='GPS fix type';
  csvNumSats='Num sats';
  csvCOG='COG';
  csvIMUtemp='IMU temp';
  csvDropRate='Drop rate';
  csvSenHealth='Sensor health';
  csvGPSen='GPS enabled';
  csvCustMode='Custom mode';
  csvMAVstate='MAV state';
  csvMAVmode='MAV mode flag';
  csvMAVland='MAV landed state';
  csvVacc='V_Acc';
  csvHacc='H_Acc';
  csvHDOP='HDOP';
  csvVDOP='VDOP';
  csvHSpeed='hSpeed';
  csvTas='tas';
  csvRoll='roll';
  csvPitch='pitch';
  csvYaw='yaw';
  csvMsgID='MsgID';
  csvRSSI='rssi';

  rsN_A='n/a';

